# Generated by Django 5.0.4 on 2024-04-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(blank=True, max_length=34, null=True)),
                ('item_name', models.CharField(blank=True, max_length=23, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('receive_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('received_by', models.CharField(blank=True, max_length=45, null=True)),
                ('issue_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issue_by', models.CharField(blank=True, max_length=56, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=46, null=True)),
                ('created_by', models.CharField(blank=True, max_length=23, null=True)),
                ('recorded_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
            ],
        ),
    ]
